Repository bifeldy/CommieFest, pull requests merged in 2019-12, with the labels that each got.

#8 Anjiinkkk !!!
  capacitor.config.json
  ionic.config.json
  package-lock.json
  package.json
  src/app/_shared/_components/_pickers/location-picker/location-picker.component.html
  src/app/_shared/_components/_pickers/location-picker/location-picker.component.scss
  src/app/_shared/_components/_pickers/location-picker/location-picker.component.spec.ts
  src/app/_shared/_components/_pickers/location-picker/location-picker.component.ts
  src/app/_shared/_module/shared/shared.module.ts
  src/app/_shared/_services/event.service.ts
  src/app/home/home.page.html
  src/app/list/joined-events/joined-events.page.ts
  src/app/list/my-events/add/add.module.ts
  src/app/list/my-events/add/add.page.html
  src/app/list/my-events/add/add.page.scss
  src/app/list/my-events/add/add.page.ts
  src/app/list/my-events/my-events.page.html
  src/app/list/my-events/my-events.page.ts
  src/app/search/search.page.html
  src/app/search/search.page.ts
  src/environments/environment.ts
Labels: bug, help wanted, invalid

#9 Ah Ahaha 💩💩💩💩💩💩💩💩💩
  src/app/_shared/_services/event.service.ts
  src/app/app.component.ts
  src/app/home/home.page.html
  src/app/home/home.page.ts
  src/app/list/joined-events/joined-events.page.html
  src/app/list/joined-events/joined-events.page.ts
  src/app/list/my-events/my-events.page.html
  src/app/search/search.page.html
Labels: enhancement, good first issue

#11 Fathan Bentrok
  package-lock.json
  src/app/about/about.module.ts
  src/app/about/about.page.html
  src/app/about/about.page.scss
  src/app/about/about.page.spec.ts
  src/app/about/about.page.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/list/my-events/details/details.page.html
  src/assets/member/bias.jpg
  src/assets/member/fatan.jpg
  src/assets/member/hans.jpg
  src/assets/member/rangga.jpg
  src/assets/member/tepen.jpg
Labels: help wanted

#12 Dev fathan
  src/app/_shared/_components/slider/slider.component.ts
  src/app/about/about.module.ts
  src/app/about/about.page.html
  src/app/about/about.page.ts
Labels: help wanted
